--- #! TEST ANSIBLE AND ARISTA
- hosts: LAB_Inventory
  gather_facts: no
  provider:
    host: "{{ inventory_hostname }}"
    username: admin
    password: admin
    use_ssl: yes
    authorize: yes
    transport: cli
- eos_config:
    lines: hostname {{ inventory_hostname }}

- eos_config:
    lines:
      - 10 permit ip 1.1.1.1/32 any log
      - 20 permit ip 2.2.2.2/32 any log
      - 30 permit ip 3.3.3.3/32 any log
      - 40 permit ip 4.4.4.4/32 any log
      - 50 permit ip 5.5.5.5/32 any log
    parents: ip access-list test
    before: no ip access-list test
    match: exact

- eos_config:
    lines:
      - 10 permit ip 1.1.1.1/32 any log
      - 20 permit ip 2.2.2.2/32 any log
      - 30 permit ip 3.3.3.3/32 any log
      - 40 permit ip 4.4.4.4/32 any log
    parents: ip access-list test
    before: no ip access-list test
    replace: block

